#!/usr/bin/env bash
set -euo pipefail
# Only a separate test process. No workspace secrets or database connection.
env -u DATABASE_URL -u PGHOST -u PGPORT -u PGUSER -u PGPASSWORD -u PGDATABASE \
  -u CLERK_SECRET_KEY -u CLERK_PUBLISHABLE_KEY -u VITE_CLERK_PUBLISHABLE_KEY \
  -u HERMES_API_KEY -u HERMES_ANALYSIS_ENABLED -u HERMES_BASE_URL \
  -u LLM_API_KEY -u OPENAI_API_KEY -u LLM_API_BASE -u LLM_MODEL \
  -u RESEND_API_KEY -u DELIVERY_EMAIL_FROM \
  -u WHATSAPP_ACCESS_TOKEN -u WHATSAPP_PHONE_NUMBER_ID \
  -u SUPABASE_LEADS_SERVER_KEY -u INVEST_BUSINESS_LEADS_ENABLED \
  -u STRIPE_SECRET_KEY -u STRIPE_API_KEY -u STRIPE_WEBHOOK_SECRET \
  -u SESSION_SECRET -u RESEND_WEBHOOK_SECRET -u WHATSAPP_APP_SECRET \
  -u WHATSAPP_WEBHOOK_VERIFY_TOKEN \
  NODE_ENV=test SYNTHETIC_BROWSER_TEST=1 \
  npx --no-install tsx scripts/tests/simulation-browser-server.ts
